### ISSUE TITLE
Project Listing Wireframe

### ISSUE THREAD

**Issue by ActualAbby** [storymachine/storymachine#91]
![project_listing](https://cloud.githubusercontent.com/assets/6440363/7635486/23cf3748-fa16-11e4-83c3-7d725fc47ec5.png)

**Comment by lotyrin** [comment]
:+1:

**Comment by eliza411** [comment]
This looks good and completely sufficient despite what I'm about to add. I assume the title links to the project. I imagine that it might eventually be worth adding in a not-to-distracting way, things like number of responses, number of invites on an invite project, when the project closes (or if it's open indefinitely). This isn't necessary in the short run, but since it might impact design choices it seems worth bringing up.

I'm also assuming it's the project owner or uber admin who'll see this listing. (I don't see an immediate use case for a participant who'll have the same "identity" between projects, so I don't imagine them seeing this screen.)

**Comment by lotyrin** [comment]
This is the project owner/team member's listing yes.

It's also not specified here, but in the project listing feature file we make it explicit that project titles are links and how one expects to switch between project workspaces.

Once we have some real projects and data and reporting capacity, I'd definitely like to play with what appears here, and what appears as cards on the project workspaces. It would be great to be able to, at a top level answer a bunch of questions about the state of projects without having to navigate, making sure of course that we don't pay too high a price in terms of visual noise for that.

**Comment by eliza411** [comment]
Should we set a milestone for importing the devops project, at least everything approved for public sharing ... it's the very first thing needed in production, and the collection form is completely specified. It will get smaller, perhaps, but not bigger. Let's revisit after M1.
